title: Start Panel
# preset: pages
unlisted: true

columns:
  # main
  main:
    width: 2/3
    sections:

      # a simple form
      content:
        type: fields
        fields:
          phone_number:
            label: Telefonnummer
            type: tel
          mail:
            label: E-Mail
            type: email
          address:
            label: Adresse
            type: text
          address_url:
            label: Link zu Karte
            type: url

  # sidebar
  sidebar:
    width: 1/3
    sections:

      # a list of subpages
      pages:
        type: pages
        headline: Seiten

tabs:

  work:
    label: Work
    
    sections:
      work:
        headline: Work
        type: pages